#!/usr/bin/env python

import sys

from rqt_bag_annotator.annotator import Annotator
from rqt_gui.main import Main

plugin = 'rqt_bag_annotator.annotator.Annotator'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin, plugin_argument_provider=Annotator.add_arguments))
